# Generated by Django 6.0.7 on 2026-08-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('ingredients', models.JSONField()),
            ],
        ),
    ]
